version: "3.7"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment: 
      - SECRET_KEY='=1nappu0f=%p)i6^4r&6_sb@9f)-vo9j1k4-bb+v%xvij$k1d^'
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_8Kao8rucdliPnmI9GfO4Zq1f00HZaqw1U8
      - STRIPE_TEST_SECRET_KEY=sk_test_aS7Hdm4G3IAKmGz5kPNmsy5o00V9L98isS
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
