# Generated by Django 2.2.6 on 2019-10-12 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20191011_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 12, 8, 25, 35, 230279, tzinfo=utc)),
        ),
    ]
