# Generated by Django 2.2.7 on 2019-12-15 03:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('platform', models.CharField(choices=[('X', 'Xbox'), ('PS', 'PS4'), ('S', 'Switch'), ('PC', 'PC'), ('M', 'Mobile')], default='', max_length=2)),
                ('genre_tages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('box_art', models.CharField(max_length=100)),
            ],
        ),
    ]
