# Generated by Django 2.2.7 on 2019-12-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=59.99, max_digits=5),
        ),
    ]
