# Generated by Django 2.2.7 on 2019-12-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191215_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('X', 'Xbox'), ('PS', 'PS4'), ('S', 'Switch'), ('PC', 'PC')], default='', max_length=2),
        ),
    ]
