# Generated by Django 2.2.6 on 2019-10-09 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20191008_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 9, 5, 42, 38, 426016, tzinfo=utc)),
        ),
    ]
