# Generated by Django 2.2.6 on 2019-10-11 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20191011_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='box_art',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 11, 11, 37, 54, 100531, tzinfo=utc)),
        ),
    ]
