# Generated by Django 2.2.6 on 2019-10-12 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20191012_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('p', 'Payment Recieved'), ('pe', 'Pending'), ('pa', 'Packing'), ('s', 'Shippped')], default='pe', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 12, 8, 59, 47, 696316, tzinfo=utc)),
        ),
    ]
