# Generated by Django 3.0.3 on 2020-02-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_auto_20200216_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=59.99, max_digits=5),
        ),
    ]
