# Generated by Django 3.0.3 on 2020-02-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_auto_20200216_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('X', 'Xbox'), ('PS', 'PS4'), ('S', 'Switch'), ('PC', 'PC')], default='', max_length=2),
        ),
    ]
