# Generated by Django 3.0.3 on 2020-02-17 02:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 17, 2, 43, 38, 386084, tzinfo=utc)),
        ),
    ]
