# Generated by Django 3.0.3 on 2020-04-03 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200217_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 3, 3, 33, 2, 375528, tzinfo=utc)),
        ),
    ]
